services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=projen
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d=projen"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
