spring:
  application:
    name: projen
  
  datasource:
    url: jdbc:postgresql://localhost:5432/projen
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
          temperature: 0.7
jwt:
  secret: cdac6c938a4fdef401313a55749b77707c1c635b3f70240762daa0a98b857e7b
