spring:
  application:
    name: projen
  
  datasource:
    url: jdbc:postgresql://localhost:5432/projen
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  ai:
    openai:
      api-key: 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
      chat:
        options:
          model: gpt-4o
          temperature: 0.7
  config:
    additional-location: classpath:secrets.yml
jwt:
  secret: cdac6c938a4fdef401313a55749b77707c1c635b3f70240762daa0a98b857e7b
