spring:
  application:
    name: projen
  
  datasource:
    url: jdbc:postgresql://localhost:5432/projen
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  ai:
    openai:
      api-key: sk-4e1a2d3b4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z
  config:
    additional-location: classpath:secrets.yml
jwt:
  secret: cdac6c938a4fdef401313a55749b77707c1c635b3f70240762daa0a98b857e7b

